//localhost

###GET all lengths
GET http://localhost:3000/lengths
###GET length by id
GET http://localhost:3000/lengths/6832335b185b3ba5c8d90952
###POST create length
POST http://localhost:3000/lengths
Content-Type: application/json

{
  "code": "5.1",
  "name": "string",
  "length_mm": 18.5
}

###PUT update length
PUT http://localhost:3000/lengths/6832335b185b3ba5c8d90952 
Content-Type: application/json

{
    "code":"5.2",
  "name": "test length",
  "length_mm": 17.4
}

###DELETE length by id
DELETE http://localhost:3000/lengths/6832335b185b3ba5c8d90952

